included:
  - Sources
  - Tests
excluded:
  - .build
  - .swiftpm
  - .venv
  - Package.swift

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - vertical_parameter_alignment_on_call

disabled_rules:
  - trailing_comma
  - opening_brace
  - nesting
  - cyclomatic_complexity
  - type_name
  - shorthand_operator
  - force_try

identifier_name:
  min_length:
    warning: 0
    error: 0
  allowed_symbols: ["_"]

large_tuple:
  warning: 10
  error: 10

line_length:
  warning: 120
  error: 120

function_body_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 3000
  error: 10000

file_length:
  warning: 10000
  error: 20000

